# Write Kubernetes Deployment Script

# Specifies the API version used to create the deployment resource
apiVersion: apps/v1

# Indicates the type of Kubernetes resource
kind: Deployment

# Contains metadata about the deployment
metadata:
  name: book-catalog
spec:
  replicas: 1   # Specific the number of pod replicas to run, here we set 1 means only one instance
  selector:    # Defines how the Deployment finds which Pods to manage.
    matchLabels:
      app: book-catalog
  template:   # Defines the template for the pods that will be created by the Deployment.
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:  # List the containers to run in each pod.
      - name: book-catalog  # The name of container.
        image: book_catalog:latest # this s we tagger docuker image witt latest.
        imagePullPolicy: Never  # This setting tells Kubernetes not to pull the Docker image from a registry.
        env: # Environment
        - name: DATABASE_URL # The envirnment variable name and PostgreSQL database 
          value: "postgresql://sit722_6_2_user:So1bs6V6BF9tIyKJ301ipCRSGNejhUP3@dpg-crck4od2ng1s73ctfndg-a.oregon-postgres.render.com/sit722_6_2"
---

apiVersion: v1  # Specific the API version
kind: Service # Indicates the type of Kubernetes resource.
metadata:
  name: book-catalog # Set the name of the service
spec:
  selector:
    app: book-catalog # It matches pods with the label app:book_catalog.
  type: NodePort # Exposes the service on each Node's IP at a static port.
  ports:
    - protocol: TCP  # The protocol to use.
      port: 8000 # The port that the service will listen on internally within Kubernetes cluster.
      targetPort: 8000 # The port on the container that the services should forward traffic to.
      nodePort: 30000 # The port on the Kubernetes node that the service is exposed on.